[package]
name = "goto"
version = "2.4.1"
authors = ["Bill Fraser <wfraser@codewise.org>"]
edition = "2021"

[dependencies]
dirs = "5"
docopt = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
