[package]
name = "goto"
version = "2.4.2"
authors = ["Bill Fraser <wfraser@codewise.org>"]
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
dirs = "5"
toml = "0.8"
